export const BFF_BASE_URL = process.env.NEXT_PUBLIC_API_URL || ":8082/api/bff"
export const CATEGORY_SERVICE_BASE_URL = process.env.NEXT_PUBLIC_CATEGORY_SERVICE_URL || ":8080/api"
export const TRANSACTION_SERVICE_BASE_URL = process.env.NEXT_PUBLIC_TRANSACTION_SERVICE_URL || ":8081/api"